// 20-color palette for "Color the Animal"
export const COLORS = [
  { name: 'Red',       hex: '#e74c3c' },
  { name: 'Orange',    hex: '#e67e22' },
  { name: 'Yellow',    hex: '#f1c40f' },
  { name: 'Green',     hex: '#2ecc71' },
  { name: 'Blue',      hex: '#3498db' },
  { name: 'Purple',    hex: '#8e44ad' },
  { name: 'Pink',      hex: '#ff9ff3' },
  { name: 'Brown',     hex: '#8b5a2b' },
  { name: 'Black',     hex: '#222222' },
  { name: 'Gray',      hex: '#95a5a6' },
  { name: 'White',     hex: '#ffffff' },
  { name: 'Hot Pink',  hex: '#ff1493' },
  { name: 'Lime',      hex: '#a4f721' },
  { name: 'Teal',      hex: '#1abc9c' },
  { name: 'Gold',      hex: '#d4af37' },
  { name: 'Lavender',  hex: '#b497d6' },
  { name: 'Peach',     hex: '#ffcba4' },
  { name: 'Magenta',   hex: '#ff00ff' },
  { name: 'Navy',      hex: '#1a3a6e' },
  { name: 'Mint',      hex: '#98ff98' },
  { name: 'Sky Blue',  hex: '#87ceeb' },
]
